import pro1 from "../assets/pro1.jpg";
import pro2 from "../assets/pro2.jpg";
import pro3 from "../assets/pro3.jpg";


const ProjectCardData = [
    {
        imgsrc: pro1,
        title: "Named entity recognition",
        text:"Named entity recognition (NER) ‒ also called entity identification or entity extracting is a natural language processing (NLP) technique that automatically identifies named entities in a text and classifies them into predefined categories  Entities can be names of people, organizations, locations, times, quantities, monetary values,percentages, and more." ,
        view :"/contact",
        source:"",
    },
    {
        imgsrc: pro2,
        title: "Generating articles using gpt-2 ",
        text:"Given some text from an unknown author, could you determine whether it was written by a human, or generated by a machine?.Language generation is one of those natural language tasks that can really produce an incredible feeling of awe at how far the fields of machine learning and artificial intelligence have come." ,
        view :"url",
        source:"url",
    },
    {
        imgsrc: pro3,
        title: " Generative Models and the Predictive Mind",
        text:"Most abstractly, a generative model can be understood as a structure designed to generate a range of phenomena in a way that is intended to model the process by which those phenomena are actually generated. If the process is causal, it is a causal generative model. If it decomposes this generative process hierarchically, it is a deep (i.e. hierarchical multi-level) causal generative model. " ,
              view :"url",
              source:"url",
    },

];
export default ProjectCardData;